export {MenuPage} from  './menu/menu';
export {MenuTabPage} from './menu-tab/menu-tab';
export {MainMenuPage} from './main-menu/main-menu';
export {PedidoActualPage} from './pedido-actual/pedido-actual';
export {ProductoPage} from './producto/producto';
export {PedidosPage} from './pedidos/pedidos';
export {PerfilPage} from './perfil/perfil';
export {CategoriaPage} from './categoria/categoria';
export {LoginPage} from './login/login';
